version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - SECRET_KEY=please-change-me
      # Optional: DATABASE_URL=sqlite:////app/database/site.db
    volumes:
      - db-data:/app/database
    entrypoint: ["sh", "/app/entrypoint.sh"]
    command: ["gunicorn", "-w", "2", "-k", "gthread", "-t", "120", "-b", "0.0.0.0:5000", "wsgi:app"]
    restart: always

volumes:
  db-data:
