"""add site settings

Revision ID: 6e976db93cb2
Revises: 2a6f9b3d9d2a
Create Date: 2025-09-23 22:32:20.010170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e976db93cb2'
down_revision = '2a6f9b3d9d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hide_prelim_rounds', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
