"""empty message

Revision ID: 8c83d5a74aa9
Revises: 1b60f3cff67e
Create Date: 2024-06-22 22:59:13.038159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c83d5a74aa9'
down_revision = '1b60f3cff67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round1_qualified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('round2_qualified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('round3_qualified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('round4_qualified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('round5_qualified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('round6_qualified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('round6_qualified')
        batch_op.drop_column('round5_qualified')
        batch_op.drop_column('round4_qualified')
        batch_op.drop_column('round3_qualified')
        batch_op.drop_column('round2_qualified')
        batch_op.drop_column('round1_qualified')

    # ### end Alembic commands ###
