"""empty message

Revision ID: bb261ad04708
Revises: ee223974af71
Create Date: 2024-06-25 15:42:21.551288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb261ad04708'
down_revision = 'ee223974af71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zwischenrunde_qualified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('final_qualified', sa.Boolean(), nullable=True))
        batch_op.drop_column('round4_qualified')
        batch_op.drop_column('round5_qualified')
        batch_op.drop_column('round6_qualified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round6_qualified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('round5_qualified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('round4_qualified', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('final_qualified')
        batch_op.drop_column('zwischenrunde_qualified')

    # ### end Alembic commands ###
