"""empty message

Revision ID: ee223974af71
Revises: 8c83d5a74aa9
Create Date: 2024-06-25 15:08:22.048677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee223974af71'
down_revision = '8c83d5a74aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('round2_passed')
        batch_op.drop_column('round3_passed')
        batch_op.drop_column('round4_passed')
        batch_op.drop_column('round1_passed')
        batch_op.drop_column('round5_passed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round5_passed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('round1_passed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('round4_passed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('round3_passed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('round2_passed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
